apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-lc-opsgenie
  namespace: aqua
spec:
  replicas: 1
  selector:
     matchLabels:
       app: aqua-lc-opsgenie
  template:
    metadata:
       labels:
         app: aqua-lc-opsgenie
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
               - key: node-role.kubernetes.io/master
                 operator: Exists
      serviceAccount: aqua-sa
      imagePullSecrets:
      - name: aqua-registry
      restartPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: aqua-lc-opsgenie
        image: aquasec/log-collector:latest
        imagePullPolicy: IfNotPresent
        env:
  #Aqua Connection properties
        - name: "INPUT_PROPERTIES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "aqua-secrets"
              key: "psql-password"
        - name: "INPUT_PROPERTIES_USERNAME"
          value: "postgres"
        - name: "INPUT_PROPERTIES_DATABASE"
          value: "slk_audit"
        - name: "INPUT_PROPERTIES_HOST"
          value: "aqua-database"
        - name: "INPUT_PROPERTIES_PORT"
          value: "5432"
        - name: "INPUT_PROPERTIES_TABLE"
          value: "audit"
#Common Connection properties
        - name: "COMMON_STORAGE_PROPERTIES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "aqua-secrets"
              key: "psql-password"
        - name: "COMMON_STORAGE_PROPERTIES_USERNAME"
          value: "postgres"
        - name: "COMMON_STORAGE_PROPERTIES_DATABASE"
          value: "logcollector"
        - name: "COMMON_STORAGE_PROPERTIES_HOST"
          value: "aqua-database"
        - name: "COMMON_STORAGE_PROPERTIES_PORT"
          value: "5432"
        - name: "COMMON_STORAGE_PROPERTIES_TABLE"
          value: "logcollector_storage"
        - name: "COMMON_STORAGE_PROPERTIES_CONNECTIONSTRING"
#         value: "postgresql://$(COMMON_STORAGE_PROPERTIES_HOST):$(COMMON_STORAGE_PROPERTIES_PORT)/$(COMMON_STORAGE_PROPERTIES_DATABASE)?user=$(COMMON_STORAGE_PROPERTIES_USERNAME)&password=$(COMMON_STORAGE_PROPERTIES_PASSWORD)&sslmode=disable"
#Opsgenie Connection properties
        - name: "OUTPUT_PROPERTIES_OPSGENIEAPIKEY"
          valueFrom:
            secretKeyRef:
              name: "lc-secrets"
              key: "opsgenie-apikey"
#         value: "41094637-4f91-4a72-aa0d-06cd29c8432f"
        - name: "OUTPUT_PROPERTIES_OPSGENIEAPIALERTURL"
          value: "https://api.opsgenie.com/v2/alerts"
        - name: "OUTPUT_PROPERTIES_ALERTRESPONDERS"
          value: "{\"username\":\"responder1@email.com\", \"type\":\"user\"},{\"username\":\"responder2@email.com\", \"type\":\"user\"}"
        - name: "OUTPUT_PROPERTIES_ALERTVISIBLETO"
          value: "{\"username\":\"your.email@mail.com\", \"type\":\"user\"}"
        - name: "OUTPUT_PROPERTIES_ALERTUSER"
          value: "AlertUser"
        - name: "OUTPUT_PROPERTIES_ALERTSOURCE"
          value: "AlertSource"
        - name: "OUTPUT_PROPERTIES_ALERTENTITY"
          value: "AlertEntity"
#Core config mount and path
        - name: "CORE_CONFIG"
          value: "/app/config/core_config_opsgenie.json"
        volumeMounts:
          - mountPath: /app/config
            name: lc-opsgenie-config
      volumes:
        - name: lc-opsgenie-config
          configMap:
            name: aqua-lc-opsgenie-config
